@echo off
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Setting up environment...
echo Please edit the .env file and add your Qianwen API key
echo Installation complete! Use 'python main.py' to start the application
pause